### ISSUE TITLE
not works in ` kitty nvim +':term nvim'`

### ISSUE THREAD

**Issue by haolian9** [phaazon/notisys.nvim#1]
lol, i know that's a rare edge case that nobody will try this, and nothing can be done in this plugin. i just point it out

**Comment by haolian9** [comment]
well, `$TERM` can be used to tell whether this function will work or not.
in my case, kitty will set TERM=xterm-kitty

**Comment by phaazon** [comment]
I understand nothing about what you just said :laughing:

**Comment by haolian9** [comment]
oh, i put more details

* open kitty
* open another nvim inside nvim terminal
* and do `:lua vim.notify('hi')`

1&2 == `kitty nvim +':term nvim'`

in this situation, you will see no notify occurs

**Comment by phaazon** [comment]
Opening nvim inside an nvim terminal… yeah, I don’t think that’s supposed to work. I’ll mark the issue as won’t fix since as you said, I don’t expect people doing this and I don’t see any way to fix it.
